// English 5-letter word list
// Used for daily word selection and guess validation
const WORDS: string[] = [
  // A
  "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT", "ADULT",
  "AFTER", "AGAIN", "AGENT", "AGILE", "AGING", "AGONY", "AGREE", "AHEAD",
  "ALARM", "ALBUM", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLEY", "ALLOT",
  "ALLOW", "ALONE", "ALONG", "ALTER", "AMPLE", "ANGEL", "ANGER", "ANGLE",
  "ANGRY", "ANIME", "ANKLE", "ANNEX", "ANTIC", "APART", "APPLE", "APPLY",
  "ARENA", "ARISE", "ARMOR", "AROMA", "ARRAY", "ARROW", "ASIDE", "ASSET",
  "ATLAS", "ATTIC", "AUDIO", "AUDIT", "AVOID", "AWAIT", "AWAKE", "AWARD",
  "AWARE", "AWFUL",
  // B
  "BADGE", "BADLY", "BAGEL", "BAKER", "BASES", "BASIC", "BASIN", "BASIS",
  "BATCH", "BEACH", "BEARD", "BEAST", "BEGIN", "BEING", "BELOW", "BENCH",
  "BERRY", "BIBLE", "BIRTH", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK",
  "BLAST", "BLAZE", "BLEAK", "BLEED", "BLEND", "BLESS", "BLIND", "BLISS",
  "BLOCK", "BLOKE", "BLOOD", "BLOOM", "BLOWN", "BOARD", "BOAST", "BONUS",
  "BOOTH", "BOUND", "BRAIN", "BRAND", "BRAVE", "BREAD", "BREAK", "BREED",
  "BRICK", "BRIDE", "BRIEF", "BRING", "BRINK", "BROAD", "BROKE", "BROOK",
  "BROWN", "BRUSH", "BUILD", "BUILT", "BUNCH", "BURST", "BUYER",
  // C
  "CABIN", "CABLE", "CAMEL", "CANDY", "CARGO", "CARRY", "CATCH", "CATER",
  "CAUSE", "CEASE", "CHAIN", "CHAIR", "CHALK", "CHAMP", "CHAOS", "CHARM",
  "CHART", "CHASE", "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEER", "CHESS",
  "CHEST", "CHIEF", "CHILD", "CHILL", "CHINA", "CHOIR", "CHOSE", "CHUNK",
  "CIVIC", "CIVIL", "CLAIM", "CLASH", "CLASS", "CLEAN", "CLEAR", "CLERK",
  "CLICK", "CLIFF", "CLIMB", "CLING", "CLOCK", "CLONE", "CLOSE", "CLOTH",
  "CLOUD", "COACH", "COAST", "COLOR", "COMET", "COMIC", "CORAL", "COUCH",
  "COUNT", "COUPE", "COURT", "COVER", "CRACK", "CRAFT", "CRANE", "CRASH",
  "CRAZY", "CREAM", "CREEK", "CREST", "CRIME", "CRISP", "CROSS", "CROWD",
  "CRUEL", "CRUSH", "CURVE", "CYCLE",
  // D
  "DAILY", "DANCE", "DATUM", "DEBUT", "DECAY", "DECOR", "DECOY", "DELTA",
  "DEMON", "DENSE", "DEPOT", "DEPTH", "DERBY", "DEVIL", "DIARY", "DIRTY",
  "DITCH", "DIZZY", "DODGE", "DONOR", "DOUBT", "DOUGH", "DRAFT", "DRAIN",
  "DRAKE", "DRAMA", "DRANK", "DRAWN", "DREAD", "DREAM", "DRESS", "DRIED",
  "DRIFT", "DRILL", "DRINK", "DRIVE", "DRONE", "DROWN", "DRUNK", "DRYER",
  "DUMMY", "DUSTY", "DWELL",
  // E
  "EAGER", "EAGLE", "EARLY", "EARTH", "EATEN", "ELDER", "ELECT", "ELITE",
  "EMAIL", "EMBER", "EMPTY", "ENACT", "ENEMY", "ENJOY", "ENTER", "ENTRY",
  "EQUAL", "EQUIP", "ERODE", "ERROR", "ESSAY", "EVENT", "EVERY", "EXACT",
  "EXERT", "EXILE", "EXIST", "EXTRA",
  // F
  "FABLE", "FACED", "FACET", "FAITH", "FALSE", "FANCY", "FATAL", "FAULT",
  "FEAST", "FENCE", "FETCH", "FEVER", "FIBER", "FIELD", "FIERY", "FIFTH",
  "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED", "FLAME", "FLASH", "FLASK",
  "FLEET", "FLESH", "FLOAT", "FLOCK", "FLOOD", "FLOOR", "FLORA", "FLOUR",
  "FLUID", "FLUSH", "FLUTE", "FOCAL", "FOCUS", "FORCE", "FORGE", "FORTH",
  "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH", "FRONT", "FROST",
  "FROZE", "FRUIT", "FULLY", "FUNNY", "FUZZY",
  // G
  "GAUGE", "GENRE", "GHOST", "GIANT", "GIVEN", "GLARE", "GLASS", "GLEAM",
  "GLOBE", "GLOOM", "GLORY", "GLOSS", "GLOVE", "GOING", "GRACE", "GRADE",
  "GRAIN", "GRAND", "GRANT", "GRAPE", "GRAPH", "GRASP", "GRASS", "GRAVE",
  "GREAT", "GREEN", "GREET", "GRIEF", "GRILL", "GRIND", "GRIPE", "GROAN",
  "GROOM", "GROSS", "GROUP", "GROVE", "GROWL", "GROWN", "GUARD", "GUESS",
  "GUEST", "GUIDE", "GUILD", "GUILT", "GUISE",
  // H
  "HABIT", "HARSH", "HASTE", "HATCH", "HAUNT", "HAVEN", "HEART", "HEAVY",
  "HEDGE", "HEFTY", "HEIST", "HELLO", "HERBS", "HINTS", "HOBBY", "HOMER",
  "HONEY", "HONOR", "HORSE", "HOTEL", "HOUSE", "HOVER", "HUMAN", "HUMOR",
  "HUNTS", "HURRY", "HYPER",
  // I
  "IMAGE", "IMPLY", "INDEX", "INDIE", "INFER", "INNER", "INPUT", "INTER",
  "IRONY", "IVORY", "ISSUE",
  // J
  "JEWEL", "JOINT", "JOKER", "JUDGE", "JUICE", "JUICY", "JUMBO",
  // K
  "KAYAK", "KNACK", "KNEEL", "KNELT", "KNIFE", "KNOCK", "KNOWN",
  // L
  "LABEL", "LABOR", "LANCE", "LARGE", "LASER", "LATCH", "LATER", "LAUGH",
  "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEMON", "LEVEL",
  "LEVER", "LIGHT", "LIKEN", "LIMIT", "LINEN", "LINER", "LIVER", "LOCAL",
  "LODGE", "LOGIC", "LONER", "LOOSE", "LORRY", "LOVER", "LOWER", "LOYAL",
  "LUNAR", "LUNCH", "LYRIC",
  // M
  "MAGIC", "MAJOR", "MAKER", "MANGA", "MANOR", "MAPLE", "MARCH", "MATCH",
  "MAYOR", "MEDAL", "MEDIA", "MERCY", "MERGE", "MERIT", "MERRY", "METAL",
  "METER", "MICRO", "MIDST", "MIGHT", "MINOR", "MINUS", "MIRTH", "MISER",
  "MIXED", "MODEL", "MODEM", "MONEY", "MONTH", "MORAL", "MOTOR", "MOUNT",
  "MOURN", "MOUSE", "MOUTH", "MOVIE", "MUDDY", "MURAL", "MUSIC", "MYTHS",
  // N
  "NAIVE", "NAKED", "NERVE", "NEVER", "NEWLY", "NICHE", "NIGHT", "NOBLE",
  "NOISE", "NORTH", "NOTCH", "NOTED", "NOVEL", "NURSE",
  // O
  "OCCUR", "OCEAN", "OLIVE", "ONSET", "OPERA", "ORBIT", "ORDER", "OTHER",
  "OUGHT", "OUNCE", "OUTER", "OWNER", "OXIDE",
  // P
  "PANEL", "PANIC", "PAPER", "PASTE", "PATCH", "PAUSE", "PEACE", "PEACH",
  "PEARL", "PEDAL", "PENNY", "PHASE", "PHONE", "PHOTO", "PIANO", "PIECE",
  "PILOT", "PINCH", "PITCH", "PIXEL", "PLACE", "PLAIN", "PLANE", "PLANT",
  "PLATE", "PLAZA", "PLEAD", "PLUCK", "PLUMB", "PLUMP", "POINT", "POLAR",
  "POUND", "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRIOR",
  "PRIZE", "PROBE", "PRONE", "PROOF", "PROSE", "PROUD", "PROVE", "PROWL",
  "PROXY", "PULSE", "PUPIL", "PURSE",
  // Q
  "QUAKE", "QUEEN", "QUERY", "QUEST", "QUEUE", "QUICK", "QUIET", "QUIRK",
  "QUOTA", "QUOTE",
  // R
  "RADAR", "RALLY", "RANCH", "RANGE", "RAPID", "RATIO", "REACH", "REALM",
  "REBEL", "REFER", "REIGN", "RELAX", "RELAY", "REMIT", "RENAL", "RENEW",
  "REPLY", "RIDER", "RIDGE", "RIFLE", "RIGHT", "RIGID", "RISKY", "RIVAL",
  "RIVER", "ROBOT", "ROCKY", "ROGUE", "ROMAN", "ROOST", "ROUGH", "ROUND",
  "ROUTE", "ROYAL", "RUINS", "RULER", "RURAL", "RUSTY",
  // S
  "SAINT", "SALAD", "SALON", "SANDY", "SAUCE", "SCALE", "SCARE", "SCENE",
  "SCENT", "SCOPE", "SCORE", "SCOUT", "SCRAP", "SEDAN", "SENSE", "SERVE",
  "SETUP", "SEVEN", "SHADE", "SHAFT", "SHALL", "SHAME", "SHAPE", "SHARE",
  "SHARK", "SHARP", "SHEAR", "SHEET", "SHELF", "SHELL", "SHIFT", "SHINE",
  "SHIRT", "SHOCK", "SHORE", "SHORT", "SHOUT", "SIGHT", "SIGMA", "SINCE",
  "SIXTH", "SIXTY", "SIZED", "SKATE", "SKILL", "SKULL", "SLASH", "SLATE",
  "SLAVE", "SLEEP", "SLICE", "SLIDE", "SLOPE", "SMALL", "SMART", "SMELL",
  "SMILE", "SMITH", "SMOKE", "SNACK", "SNAKE", "SOLAR", "SOLID", "SOLVE",
  "SONIC", "SORRY", "SOUND", "SOUTH", "SPACE", "SPARE", "SPARK", "SPEAK",
  "SPEAR", "SPEED", "SPELL", "SPEND", "SPICE", "SPINE", "SPOKE", "SPOON",
  "SPORT", "SPRAY", "SQUAD", "STACK", "STAFF", "STAGE", "STAIN", "STAKE",
  "STALE", "STALL", "STAMP", "STAND", "STARE", "START", "STATE", "STAYS",
  "STEAK", "STEAL", "STEAM", "STEEL", "STEEP", "STEER", "STERN", "STICK",
  "STIFF", "STILL", "STING", "STOCK", "STOLE", "STONE", "STOOD", "STORE",
  "STORM", "STORY", "STOUT", "STOVE", "STRAP", "STRAW", "STRAY", "STRIP",
  "STUCK", "STUDY", "STUFF", "STUMP", "STUNG", "STYLE", "SUGAR", "SUITE",
  "SUPER", "SURGE", "SWAMP", "SWEAR", "SWEAT", "SWEET", "SWEPT", "SWIFT",
  "SWING", "SWORD",
  // T
  "TABLE", "TASTE", "TEACH", "TEMPO", "TENOR", "TENSE", "TENTH", "TERMS",
  "THEFT", "THEME", "THERE", "THICK", "THIEF", "THING", "THINK", "THIRD",
  "THORN", "THREE", "THREW", "THROW", "THUMB", "TIGER", "TIGHT", "TIMER",
  "TITLE", "TOAST", "TODAY", "TOKEN", "TOPIC", "TOTAL", "TOUCH", "TOUGH",
  "TOWEL", "TOWER", "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN",
  "TRAIT", "TRASH", "TREAT", "TREND", "TRIAL", "TRIBE", "TRICK", "TROOP",
  "TRUCK", "TRULY", "TRUMP", "TRUNK", "TRUST", "TRUTH", "TUMOR", "TWICE",
  "TWIST",
  // U
  "ULTRA", "UNCLE", "UNDER", "UNFIT", "UNION", "UNITY", "UNTIL", "UPPER",
  "UPSET", "URBAN", "USAGE", "USUAL", "UTTER",
  // V
  "VAGUE", "VALID", "VALUE", "VAULT", "VENUE", "VERSE", "VIDEO", "VIGOR",
  "VINYL", "VIOLA", "VIPER", "VIRAL", "VIRUS", "VISIT", "VISTA", "VITAL",
  "VIVID", "VOCAL", "VODKA", "VOICE", "VOTER",
  // W
  "WAGES", "WASTE", "WATCH", "WATER", "WEARY", "WEAVE", "WEDGE", "WEIRD",
  "WHEAT", "WHEEL", "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE", "WHOSE",
  "WIDTH", "WITCH", "WOMAN", "WORLD", "WORRY", "WORSE", "WORST", "WORTH",
  "WOULD", "WOUND", "WRATH", "WRITE", "WRONG", "WROTE",
  // Y
  "YACHT", "YIELD", "YOUNG", "YOUTH",
  // Z
  "ZEBRA", "ZONES",
];

// Filter only exact 5-letter words (safety check)
export const VALID_WORDS_EN = WORDS.filter((w) => w.length === 5);
