import type { WordEntry } from "./types";

export const WORDS_TR: WordEntry[] = [
  // Hayvanlar
  { word: "ASLAN", category: "Hayvanlar" },
  { word: "KAPLAN", category: "Hayvanlar" },
  { word: "KARTAL", category: "Hayvanlar" },
  { word: "YUNUS", category: "Hayvanlar" },
  { word: "KELEBEK", category: "Hayvanlar" },
  { word: "PENGUEN", category: "Hayvanlar" },
  { word: "TIMSAH", category: "Hayvanlar" },
  { word: "ZURAFA", category: "Hayvanlar" },
  { word: "FİL", category: "Hayvanlar" },
  { word: "TAVŞAN", category: "Hayvanlar" },
  { word: "PAPAĞAN", category: "Hayvanlar" },
  { word: "KANGURU", category: "Hayvanlar" },
  { word: "BAYKUŞ", category: "Hayvanlar" },
  { word: "AHTAPOT", category: "Hayvanlar" },
  { word: "FLAMINGO", category: "Hayvanlar" },

  // Yiyecekler
  { word: "PIZZA", category: "Yiyecekler" },
  { word: "HAMBURGER", category: "Yiyecekler" },
  { word: "ÇORBA", category: "Yiyecekler" },
  { word: "MAKARNA", category: "Yiyecekler" },
  { word: "BÖREK", category: "Yiyecekler" },
  { word: "BAKLAVA", category: "Yiyecekler" },
  { word: "DONDURMA", category: "Yiyecekler" },
  { word: "SIMIT", category: "Yiyecekler" },
  { word: "KÖFTE", category: "Yiyecekler" },
  { word: "PİLAV", category: "Yiyecekler" },
  { word: "LAHMACUN", category: "Yiyecekler" },
  { word: "DOLMA", category: "Yiyecekler" },
  { word: "KEBAP", category: "Yiyecekler" },
  { word: "MANTARLI", category: "Yiyecekler" },
  { word: "ÇIKOLATA", category: "Yiyecekler" },

  // Ülkeler
  { word: "TÜRKİYE", category: "Ülkeler" },
  { word: "ALMANYA", category: "Ülkeler" },
  { word: "FRANSA", category: "Ülkeler" },
  { word: "İNGİLTERE", category: "Ülkeler" },
  { word: "JAPONYA", category: "Ülkeler" },
  { word: "BREZİLYA", category: "Ülkeler" },
  { word: "KANADA", category: "Ülkeler" },
  { word: "AVUSTRALYA", category: "Ülkeler" },
  { word: "İSPANYA", category: "Ülkeler" },
  { word: "İTALYA", category: "Ülkeler" },
  { word: "MISIR", category: "Ülkeler" },
  { word: "YUNANİSTAN", category: "Ülkeler" },
  { word: "PORTEKİZ", category: "Ülkeler" },
  { word: "ARJANTİN", category: "Ülkeler" },
  { word: "MEKSİKA", category: "Ülkeler" },

  // Meslekler
  { word: "DOKTOR", category: "Meslekler" },
  { word: "ÖĞRETMEN", category: "Meslekler" },
  { word: "MÜHENDİS", category: "Meslekler" },
  { word: "AVUKAT", category: "Meslekler" },
  { word: "AŞÇI", category: "Meslekler" },
  { word: "PİLOT", category: "Meslekler" },
  { word: "MİMAR", category: "Meslekler" },
  { word: "ECZACI", category: "Meslekler" },
  { word: "GAZETECİ", category: "Meslekler" },
  { word: "RESSAM", category: "Meslekler" },
  { word: "BERBER", category: "Meslekler" },
  { word: "KASAP", category: "Meslekler" },
  { word: "İTFAİYECİ", category: "Meslekler" },
  { word: "ASTRONOT", category: "Meslekler" },
  { word: "KAPTAN", category: "Meslekler" },

  // Spor
  { word: "FUTBOL", category: "Spor" },
  { word: "BASKETBOL", category: "Spor" },
  { word: "VOLEYBOL", category: "Spor" },
  { word: "TENİS", category: "Spor" },
  { word: "YÜZME", category: "Spor" },
  { word: "BOKS", category: "Spor" },
  { word: "KAYAK", category: "Spor" },
  { word: "GÜREŞ", category: "Spor" },
  { word: "BİSİKLET", category: "Spor" },
  { word: "ATLETİZM", category: "Spor" },
  { word: "OKÇULUK", category: "Spor" },
  { word: "ESKRİM", category: "Spor" },
  { word: "HALTER", category: "Spor" },
  { word: "CİMNASTİK", category: "Spor" },
  { word: "BADMINTON", category: "Spor" },

  // Doğa
  { word: "OKYANUS", category: "Doğa" },
  { word: "VOLKAN", category: "Doğa" },
  { word: "ORMAN", category: "Doğa" },
  { word: "DEPREM", category: "Doğa" },
  { word: "GÖKKUŞAĞI", category: "Doğa" },
  { word: "FIRTINA", category: "Doğa" },
  { word: "ÇÖL", category: "Doğa" },
  { word: "BUZUL", category: "Doğa" },
  { word: "ŞELALE", category: "Doğa" },
  { word: "MAĞARA", category: "Doğa" },

  // Teknoloji
  { word: "BİLGİSAYAR", category: "Teknoloji" },
  { word: "TELEFON", category: "Teknoloji" },
  { word: "İNTERNET", category: "Teknoloji" },
  { word: "ROBOT", category: "Teknoloji" },
  { word: "YAZICI", category: "Teknoloji" },
  { word: "TABLET", category: "Teknoloji" },
  { word: "UYGULAMA", category: "Teknoloji" },
  { word: "KLAVYE", category: "Teknoloji" },
  { word: "EKRAN", category: "Teknoloji" },
  { word: "YAZILIM", category: "Teknoloji" },
];
