import type { WordEntry } from "./types";

export const WORDS_EN: WordEntry[] = [
  // Animals
  { word: "ELEPHANT", category: "Animals" },
  { word: "GIRAFFE", category: "Animals" },
  { word: "DOLPHIN", category: "Animals" },
  { word: "PENGUIN", category: "Animals" },
  { word: "BUTTERFLY", category: "Animals" },
  { word: "CROCODILE", category: "Animals" },
  { word: "KANGAROO", category: "Animals" },
  { word: "OCTOPUS", category: "Animals" },
  { word: "FLAMINGO", category: "Animals" },
  { word: "CHEETAH", category: "Animals" },
  { word: "GORILLA", category: "Animals" },
  { word: "PARROT", category: "Animals" },
  { word: "RABBIT", category: "Animals" },
  { word: "LEOPARD", category: "Animals" },
  { word: "HAMSTER", category: "Animals" },

  // Food
  { word: "PIZZA", category: "Food" },
  { word: "HAMBURGER", category: "Food" },
  { word: "SPAGHETTI", category: "Food" },
  { word: "CHOCOLATE", category: "Food" },
  { word: "PANCAKE", category: "Food" },
  { word: "SANDWICH", category: "Food" },
  { word: "POPCORN", category: "Food" },
  { word: "WAFFLE", category: "Food" },
  { word: "BURRITO", category: "Food" },
  { word: "LASAGNA", category: "Food" },
  { word: "CROISSANT", category: "Food" },
  { word: "AVOCADO", category: "Food" },
  { word: "PRETZEL", category: "Food" },
  { word: "BROWNIE", category: "Food" },
  { word: "MUFFIN", category: "Food" },

  // Countries
  { word: "AUSTRALIA", category: "Countries" },
  { word: "BRAZIL", category: "Countries" },
  { word: "CANADA", category: "Countries" },
  { word: "GERMANY", category: "Countries" },
  { word: "JAPAN", category: "Countries" },
  { word: "MEXICO", category: "Countries" },
  { word: "NORWAY", category: "Countries" },
  { word: "PORTUGAL", category: "Countries" },
  { word: "SWEDEN", category: "Countries" },
  { word: "TURKEY", category: "Countries" },
  { word: "EGYPT", category: "Countries" },
  { word: "FRANCE", category: "Countries" },
  { word: "ARGENTINA", category: "Countries" },
  { word: "THAILAND", category: "Countries" },
  { word: "ICELAND", category: "Countries" },

  // Professions
  { word: "DOCTOR", category: "Professions" },
  { word: "ENGINEER", category: "Professions" },
  { word: "TEACHER", category: "Professions" },
  { word: "ARCHITECT", category: "Professions" },
  { word: "ASTRONAUT", category: "Professions" },
  { word: "MUSICIAN", category: "Professions" },
  { word: "DETECTIVE", category: "Professions" },
  { word: "SCIENTIST", category: "Professions" },
  { word: "JOURNALIST", category: "Professions" },
  { word: "CARPENTER", category: "Professions" },
  { word: "CAPTAIN", category: "Professions" },
  { word: "PAINTER", category: "Professions" },
  { word: "SURGEON", category: "Professions" },
  { word: "DENTIST", category: "Professions" },
  { word: "PHARMACIST", category: "Professions" },

  // Sports
  { word: "FOOTBALL", category: "Sports" },
  { word: "BASKETBALL", category: "Sports" },
  { word: "VOLLEYBALL", category: "Sports" },
  { word: "SWIMMING", category: "Sports" },
  { word: "ARCHERY", category: "Sports" },
  { word: "CYCLING", category: "Sports" },
  { word: "FENCING", category: "Sports" },
  { word: "CRICKET", category: "Sports" },
  { word: "GYMNASTICS", category: "Sports" },
  { word: "WRESTLING", category: "Sports" },
  { word: "BADMINTON", category: "Sports" },
  { word: "MARATHON", category: "Sports" },
  { word: "SURFING", category: "Sports" },
  { word: "KARATE", category: "Sports" },
  { word: "SKIING", category: "Sports" },

  // Nature
  { word: "OCEAN", category: "Nature" },
  { word: "VOLCANO", category: "Nature" },
  { word: "FOREST", category: "Nature" },
  { word: "RAINBOW", category: "Nature" },
  { word: "GLACIER", category: "Nature" },
  { word: "WATERFALL", category: "Nature" },
  { word: "MOUNTAIN", category: "Nature" },
  { word: "TORNADO", category: "Nature" },
  { word: "DESERT", category: "Nature" },
  { word: "ISLAND", category: "Nature" },

  // Technology
  { word: "COMPUTER", category: "Technology" },
  { word: "INTERNET", category: "Technology" },
  { word: "KEYBOARD", category: "Technology" },
  { word: "SOFTWARE", category: "Technology" },
  { word: "WEBSITE", category: "Technology" },
  { word: "PRINTER", category: "Technology" },
  { word: "BLUETOOTH", category: "Technology" },
  { word: "DATABASE", category: "Technology" },
  { word: "ALGORITHM", category: "Technology" },
  { word: "HARDWARE", category: "Technology" },
];
